[build.environment]
  DART_SASS_VERSION = "1.97.3"
  GO_VERSION = "1.26.0"
  HUGO_VERSION = "0.164.0"
  NODE_VERSION = "24.18.0"
  NPM_VERSION = "11.16.0"
  TZ = "Europe/Amsterdam"

[build]
  publish = "public"
  command = """\
  git config core.quotepath false && \
  npm install && \
  hugo build --gc --minify --baseURL "${URL}" && \
  npx pagefind --site public
  """

[context.deploy-preview]
  command = """\
  git config core.quotepath false && \
  npm install && \
  hugo build --gc --minify --baseURL "$DEPLOY_PRIME_URL" && \
  npx pagefind --site public
  """

[context.branch-deploy]
  command = """\
  git config core.quotepath false && \
  npm install && \
  hugo build --gc --minify --baseURL "$DEPLOY_PRIME_URL" && \
  npx pagefind --site public
  """

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
  from = "/js/pa-giEb4LeQ_HBOeSFnbQ2FG.js"
  to = "https://plausible.io/js/pa-giEb4LeQ_HBOeSFnbQ2FG.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "default-src 'self'; manifest-src 'self'; connect-src 'self' https://plausible.io/api/event; font-src 'self'; img-src 'self' data:; script-src 'self' https://plausible.io/js/pa-giEb4LeQ_HBOeSFnbQ2FG.js 'sha256-d2naYp9C7LmEhG5Ym6TxSt+GauEaZC4Z+I9rATlQz1E='; style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-PjBkwE8xcYZAp+HsnzzOVNqa/Ra+/v1Fnx6f0PW6ic4='; frame-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control= '''
    public,
    max-age=31536000'''
    Access-Control-Allow-Origin = "*"
